name: TruffleHog Secrets Scan
on: [push]
jobs:
  scan-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Scan secrets
        run: | 
          curl -v -L -O https://github.com/trufflesecurity/trufflehog/releases/download/v3.63.7/trufflehog_3.63.7_linux_amd64.tar.gz
          pwd
          ls -la
          tar -xzf trufflehog_3.63.7_linux_amd64.tar.gz
          ./trufflehog filesystem -j --fail ${{ github.repository }}
        